apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-aws-dynamodb
  annotations:
    meta.crossplane.io/maintainer: The configuration-aws-dynamodb Configuration
    meta.crossplane.io/source: github.com/upbound/configuration-aws-dynamodb
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration-aws-dynamodb configuration offers
      ContributorInsights, TableItem, TableReplica, and Table
      resource creation for an AWS DynamoDB instance.
    meta.crossplane.io/readme: |
      This Configuration bundles an Upbound Cloud
      extension and an API definition. The API will
      allow control planes to provision AWS DynamoDB
      instances with optional ContributorInsights,
      table replication, and an arbitrary number of
      tableItem resources using the provider-aws-dynamodb
      from the Upbound marketplace.
spec:
  crossplane:
    version: ">=v1.15.2-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-aws-dynamodb
      version: "v1.4.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: "v0.5.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: "v0.4.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-cel-filter
      version: "v0.1.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: "v0.2.1"
    - function: xpkg.upbound.io/markuss/function-aws-importer
      version: "v0.0.1"
