---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtableitemsets.dynamodb.aws.platform.upbound.io
spec:
  group: dynamodb.aws.platform.upbound.io
  names:
    kind: XTableItemSet
    plural: xtableitemsets
  claimNames:
    kind: TableItemSet
    plural: tableitemsets
  defaultCompositionRef:
    name: tableitemset.dynamodb.aws.platform.upbound.io
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: >-
                    Upbound Platform DynamoDB Table
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    hashKey:
                      description: Hash key to use for lookups and identification of
                        the item
                      type: string
                    item:
                      description: JSON representation of a map of attribute name/value
                        pairs, one for each attribute. Only the primary key attributes
                        are required; you can optionally provide other attribute name-value
                        pairs for the item.
                      type: string
                    rangeKey:
                      description: Range key to use for lookups and identification of
                        the item. Required if there is range key defined in the table.
                      type: string
                    region:
                      description: Region is the region you'd like your resource to
                        be created in.
                      type: string
                    tableItems:
                      description: >-
                        Array of tableItems.
                      items:
                        properties:
                          hashKey:
                            description: >-
                              Hash key to use for lookups and
                              identification of the item.
                            type: string
                          item:
                            description: >-
                              JSON representation of a map of
                              attribute name/value pairs, one for each
                              attribute. Only the primary key attributes
                              are required; you can optionally
                              provide other attribute name-value
                              pairs for the item.
                            type: string
                        type: object
                      type: array
                    tableName:
                      description: Name of the table to contain the item.
                      type: string
                    tableNameRef:
                      description: Reference to a Table to populate tableName.
                      properties:
                        name:
                          description: Name of the referenced object.
                          type: string
                        policy:
                          description: Policies for referencing.
                          properties:
                            resolution:
                              default: Required
                              description: |-
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              enum:
                                - Required
                                - Optional
                              type: string
                            resolve:
                              description: |-
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                              type: string
                          type: object
                      required:
                        - name
                      type: object
                    tableNameSelector:
                      description: Selector for a Table to populate tableName.
                      properties:
                        matchControllerRef:
                          description: |-
                            MatchControllerRef ensures an object with the same controller reference
                            as the selecting object is selected.
                          type: boolean
                        matchLabels:
                          additionalProperties:
                            type: string
                          description: MatchLabels ensures an object with matching labels
                            is selected.
                          type: object
                        policy:
                          description: Policies for selection.
                          properties:
                            resolution:
                              default: Required
                              description: |-
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              enum:
                                - Required
                                - Optional
                              type: string
                            resolve:
                              description: |-
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                              type: string
                          type: object
                      type: object
                    providerConfigName:
                      description: >-
                        Crossplane ProviderConfig to use for
                        provisioning the resources.
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - providerConfigName
                    - region
                  type: object
              required:
                - parameters
            status:
              properties:
                dynamodbTableItems:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
