---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: table.dynamodb.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
    kind: XTable

  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: common-parameters
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region
        resources:
          - name: table
            base:
              apiVersion: dynamodb.aws.upbound.io/v1beta1
              kind: Table
            patches:
              - type: PatchSet
                patchSetName: common-parameters
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[0].name
                toFieldPath: spec.forProvider.attribute[0].name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[0].attributeType
                toFieldPath: spec.forProvider.attribute[0].type
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[1].name
                toFieldPath: spec.forProvider.attribute[1].name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[1].attributeType
                toFieldPath: spec.forProvider.attribute[1].type
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[2].name
                toFieldPath: spec.forProvider.attribute[2].name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[2].attributeType
                toFieldPath: spec.forProvider.attribute[2].type
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[3].name
                toFieldPath: spec.forProvider.attribute[3].name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.attribute[3].attributeType
                toFieldPath: spec.forProvider.attribute[3].type
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.billingMode
                toFieldPath: spec.forProvider.billingMode
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionProtectionEnabled
                toFieldPath: spec.forProvider.deletionProtectionEnabled
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.hashKey
                toFieldPath: spec.forProvider.hashKey
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.importTable
                toFieldPath: spec.parameters.importTable
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.localSecondaryIndex
                toFieldPath: spec.parameters.localSecondaryIndex
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.pointInTimeRecovery
                toFieldPath: spec.parameters.pointInTimeRecovery
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.globalSecondaryIndex
                toFieldPath: spec.parameters.globalSecondaryIndex
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.rangeKey
                toFieldPath: spec.forProvider.rangeKey
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.readCapacity
                toFieldPath: spec.forProvider.readCapacity
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.replica
                toFieldPath: spec.forProvider.replica
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.restoreDateTime
                toFieldPath: spec.forProvider.restoreDateTime
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.restoreSourceName
                toFieldPath: spec.forProvider.restoreSourceName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.restoreToLatestTime
                toFieldPath: spec.forProvider.restoreToLatestTime
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.serverSideEncryption
                toFieldPath: spec.forProvider.serverSideEncryption
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.streamEnabled
                toFieldPath: spec.forProvider.streamEnabled
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.streamViewType
                toFieldPath: spec.forProvider.streamViewType
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tableClass
                toFieldPath: spec.forProvider.tableClass
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tags
                toFieldPath: spec.forProvider.tags
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.ttl
                toFieldPath: spec.forProvider.ttl
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.writeCapacity
                toFieldPath: spec.forProvider.writeCapacity
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider
                toFieldPath: status.dynamodbTable
