---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: table.dynamodb.aws.platform.upbound.io
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: dynamodb.aws.platform.upbound.io/v1alpha1
    kind: XTable

  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: crossplane-contrib-function-go-templating
        # name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $annotations := .observed.composite.resouce.metadata.annotations }}
            {{ $spec := .observed.composite.resource.spec }}
            {{ $tableStatus := .observed.resources.table.resource.status }}
            {{ $tableReplicaStatus := .observed.resources.tableReplica.resource.status }}
            {{ $xTableStatus := .observed.composite.resource.status }}
            {{- if $spec.parameters.tableReplica }}
            {{- if $tableStatus.atProvider }}
            ---
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: TableReplica
            metadata:
              annotations:
                {{ setResourceNameAnnotation "tableReplica" }}
            spec:
              deletionPolicy: {{ $spec.parameters.deletionPolicy }}
              forProvider:
                globalTableArn: {{ $xTableStatus.dynamodbTable.arn }}
                region: {{ $spec.parameters.tableReplicaRegion }}
                {{- if $spec.parameters.kmsKeyArn }}
                kmsKeyArn: {{ $spec.parameters.kmsKeyArn }}
                {{- end }}
                {{- if $spec.parameters.kmsKeyArnRef }}
                kmsKeyArnRef: {{ $spec.parameters.kmsKeyArnRef }}
                {{- end }}
                {{- if $spec.parameters.kmsKeyArnSelector }}
                kmsKeyArnSelector: {{ $spec.parameters.kmsKeyArnSelector }}
                {{- end }}
                {{- if $spec.parameters.pointInTimeRecovery }}
                pointInTimeRecovery: {{ $spec.parameters.pointInTimeRecovery }}
                {{- end }}
                {{- if $spec.parameters.tableClassOverride }}
                tableClassOverride: {{ $spec.parameters.tableClassOverride }}
                {{- end }}
                tags:
                {{- range $key, $value := $spec.parameters.tags }}
                  {{ $key }}: {{ $value }}
                {{- end }}
              providerConfigRef:
                name: {{ $spec.parameters.providerConfigName }}
            {{- end }}
            {{- end }}
            ---
            apiVersion: dynamodb.aws.upbound.io/v1beta1
            kind: Table
            metadata:
              annotations:
                {{ setResourceNameAnnotation "table" }}
            spec:
              deletionPolicy: {{ $spec.parameters.deletionPolicy }}
              forProvider:
                region: {{ $spec.parameters.region }}
                attribute: {{ $spec.parameters.attribute | toYaml | nindent 4 }}
                globalSecondaryIndex: {{ $spec.parameters.globalSecondaryIndex | toYaml | nindent 4 }}
                hashKey: {{ $spec.parameters.hashKey }}
                rangeKey: {{ $spec.parameters.rangeKey }}
                {{- if $spec.parameters.tableReplica }}
                billingMode: {{ $spec.parameters.billingMode }}
                {{- else }}
                billingMode: PROVISIONED
                readCapacity: {{ $spec.parameters.readCapacity }}
                writeCapacity: {{ $spec.parameters.writeCapacity }}
                {{- end }}
                {{- if $spec.parameters.pointInTimeRecovery }}
                pointInTimeRecovery:
                  enabled: {{ $spec.parameters.pointInTimeRecovery }}
                {{- end }}
                tags:
                {{- range $key, $value := $spec.parameters.tags }}
                  {{ $key }}: {{ $value }}
                {{- end }}
              providerConfigRef:
                name: {{ $spec.parameters.providerConfigName }}
            ---
            apiVersion: {{ .observed.composite.resource.apiVersion }}
            kind: XTable
            {{- if $tableStatus.atProvider }}
            status:
              dynamodbTable:
              {{ $tableStatus.atProvider | toYaml | nindent 4 }}
              {{- if $tableReplicaStatus.atProvider }}
              dynamodbTableReplica:
              {{ $tableReplicaStatus.atProvider | toYaml | nindent 4 }}
              {{- end }}
            {{- else }}
            status: {}
            {{- end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
        # name: function-auto-ready
