---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xinstances.dynamodb.aws.platform.upbound.io
spec:
  group: dynamodb.aws.platform.upbound.io
  names:
    kind: XInstance
    plural: xnstances
  claimNames:
    kind: Instance
    plural: instances
  defaultCompositionRef:
    name: instance.dynamodb.aws.platform.upbound.io
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: >-
                    Upbound Platform DynamoDB Instance
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    region:
                      description: >-
                        Region is the region you'd
                        like your resource to be created in.
                      type: string
                    providerConfigName:
                      description: >-
                        Crossplane ProviderConfig to use for
                        provisioning the resources.
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - providerConfigName
                    - region
                  type: object
              required:
                - parameters
            status:
              properties:
                contributorInsights:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTable:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTableItem:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTableReplica:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTag:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                kms:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
