---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xinstances.dynamodb.aws.platform.upbound.io
spec:
  group: dynamodb.aws.platform.upbound.io
  names:
    kind: XInstance
    plural: xinstances
  claimNames:
    kind: Instance
    plural: instances
  defaultCompositionRef:
    name: instance.dynamodb.aws.platform.upbound.io
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: >-
                    Upbound Platform DynamoDB Instance
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    attribute:
                      description: >-
                        Set of nested attribute definitions.
                        Only required for hash_key and range_key
                        attributes. See below.
                      items:
                        properties:
                          name:
                            description: >-
                              Name of the attribute
                            type: string
                          attributeType:
                            description: >-
                              Attribute type.
                              Valid values are S (string),
                              N (Number),B (binary).
                            type: string
                            enum: ["N", "S", "B"]
                        type: object
                      type: array
                    billingMode:
                      description: Controls how you are charged for read and write throughput
                        and how you manage capacity. The valid values are PROVISIONED
                        and PAY_PER_REQUEST. Defaults to PROVISIONED.
                      type: string
                    contributorInsights:
                      description: Toggle contributor insights
                      type: boolean
                    deletionProtectionEnabled:
                      description: Enables deletion protection for table. Defaults to
                        false.
                      type: boolean
                    globalSecondaryIndex:
                      description: Describe a GSI for the table; subject to the normal
                        limits on the number of GSIs, projected attributes, etc. See
                        below.
                      items:
                        properties:
                          hashKey:
                            description: Name of the hash key in the index; must be
                              defined as an attribute in the resource.
                            type: string
                          name:
                            description: Name of the index.
                            type: string
                          nonKeyAttributes:
                            description: Only required with INCLUDE as a projection
                              type; a list of attributes to project into the index.
                              These do not need to be defined as attributes on the table.
                            items:
                              type: string
                            type: array
                            x-kubernetes-list-type: set
                          projectionType:
                            description: One of ALL, INCLUDE or KEYS_ONLY where ALL
                              projects every attribute into the index, KEYS_ONLY projects  into
                              the index only the table and index hash_key and sort_key
                              attributes ,  INCLUDE projects into the index all of the
                              attributes that are defined in non_key_attributes in addition
                              to the attributes that thatKEYS_ONLY project.
                            type: string
                          rangeKey:
                            description: Name of the range key; must be defined
                            type: string
                          readCapacity:
                            description: Number of read units for this index. Must be
                              set if billing_mode is set to PROVISIONED.
                            type: number
                          writeCapacity:
                            description: Number of write units for this index. Must
                              be set if billing_mode is set to PROVISIONED.
                            type: number
                        type: object
                      type: array
                    hashKey:
                      description: >-
                        Attribute to use as the hash (partition) key.
                        Must also be defined as an attribute.
                      type: string
                    rangeKey:
                      description: >-
                        Attribute to use as the range (sort) key.
                        Must also be defined as an attribute.
                      type: string
                    readCapacity:
                      description: >-
                        Number of read units for this index.
                        Must be set if billing_mode is set to PROVISIONED.
                      type: integer
                      default: 1
                    region:
                      description: >-
                        Region is the region you'd
                        like your resource to be created in.
                      type: string
                    tableReplica:
                      description: Toggle table replica
                      type: boolean
                    tableReplicaRegion:
                      description: Must be in a different region than main table.
                      type: string
                    writeCapacity:
                      description: >-
                        Number of write units for this index.
                        Must be set if billing_mode is set to PROVISIONED.
                      type: integer
                      default: 1
                    tableItems:
                      description: >-
                        Array of tableItems.
                      items:
                        properties:
                          hashKey:
                            description: >-
                              Hash key to use for lookups and
                              identification of the item.
                            type: string
                          item:
                            description: >-
                              JSON representation of a map of
                              attribute name/value pairs, one for each
                              attribute. Only the primary key attributes
                              are required; you can optionally
                              provide other attribute name-value
                              pairs for the item.
                            type: string
                        type: object
                      type: array
                    providerConfigName:
                      description: >-
                        Crossplane ProviderConfig to use for
                        provisioning the resources.
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - providerConfigName
                    - region
                  type: object
              required:
                - parameters
            status:
              properties:
                dynamodbContributorInsights:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTable:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTableItems:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTableReplica:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                dynamodbTag:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                kms:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
